import { NextResponse } from 'next/server';
import { db } from '@/lib/server/db';
import { google } from 'googleapis';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { scheduleId, guestName, guestEmail, startTime } = body;

    const schedule = await db.getScheduleById(scheduleId);
    if (!schedule) return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });

    let eventId = '';

    if (schedule.googleRefreshToken) {
      const oauth2Client = new google.auth.OAuth2(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET
      );

      oauth2Client.setCredentials({
        access_token: schedule.googleAccessToken,
        refresh_token: schedule.googleRefreshToken,
      });

      const calendar = google.calendar({ version: 'v3', auth: oauth2Client });
      
      const startDate = new Date(startTime);
      const endDate = new Date(startDate.getTime() + schedule.durationMinutes * 60000);

      const event = {
        summary: `Booking with ${guestName}`,
        description: `Booking generated by zero-latency app.\nGuest: ${guestName} (${guestEmail})`,
        start: { dateTime: startDate.toISOString() },
        end: { dateTime: endDate.toISOString() },
        attendees: [{ email: guestEmail }],
        conferenceData: {
          createRequest: { 
            requestId: crypto.randomUUID(), 
            conferenceSolutionKey: { type: "hangoutsMeet" } 
          }
        }
      };

      const res = await calendar.events.insert({
        calendarId: 'primary',
        requestBody: event,
        conferenceDataVersion: 1,
        sendUpdates: 'all',
      });

      eventId = res.data.id || '';
      
      // If tokens changed, we'd ideally save them back, but we'll skip for now to keep it simple.
    }

    const booking = {
      id: crypto.randomUUID(),
      scheduleId,
      guestName,
      guestEmail,
      startTime,
      eventId
    };

    await db.createBooking(booking);

    return NextResponse.json({ success: true, booking });
  } catch (error: any) {
    console.error('Booking submit error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
